#! /bin/sh

### BEGIN INIT INFO
# Provides:          ssh_first
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S   
# Default-Stop:
# Short-Description: SSH on first run
# Description:       The Rest comes later
#                    starting at first time.
#                      
#                    1. regenerate ssh host key
#                    2. regenerate ajenti private key
### END INIT INFO


N=/etc/init.d/ssh-first

 
                echo "Creating IMX6 User & Creating ssh keys..." >> /dev/tty0
                (echo 123; echo 123; echo) | adduser imx6
                NEWMAC=00:01:43:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`
                sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces
                sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.hostapd
                # more output to console only in first run then to serial
                # sed -e 's/extraargs=console=tty0/extraargs=console=ttyS0,115200/g' -i /boot/uEnv.ct
                # sed -e 's/extraargs=console=tty0/extraargs=console=ttyS0,115200/g' -i /boot/uEnv.cb2
                rm /etc/ssh/ssh_host*
                dpkg-reconfigure openssh-server 
                set +e
                #echo "Creating local sources list..." 
                #netselect-apt -s -n -o /etc/apt/sources.list >/dev/null 2>&1
                echo "Downloading packages list..." 
                apt-get update >/dev/null 2>&1
                # echo "Updating all packages..." 
                # apt-get -y upgrade >/dev/null 2>&1
                # apt-get -y clean >/dev/null 2>&1
cat <<EOF >/etc/init.d/motd
#!/bin/sh
### BEGIN INIT INFO
# Provides:          motd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Create dynamic part of /etc/motd
# Description:       /etc/motd is user-editable and static.  This script
#                    creates the initial dynamic part, by default the
#                    output of uname, and stores it in /var/run/motd.dynamic.
#                    Both parts are output by pam_motd.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

do_start () {
	echo "" > /var/run/motd.dynamic
   if [ $(cat /proc/meminfo | grep MemTotal | grep -o '[0-9]\+') -ge 1531749 ]; then
           toilet -f standard -F metal "IMX6" >> /var/run/motd.dynamic 
           echo "To setup your Imx6 use the following command (sudo imx6-config)" >> /var/run/motd.dynamic
   else
           toilet -f standard -F metal  "IMX6" >> /var/run/motd.dynamic
   fi
   echo "" >> /var/run/motd.dynamic
	
}

do_status () {
	if [ -f /var/run/motd.dynamic ] ; then
		return 0
	else
		return 4
	fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: motd [start|stop|status]" >&2
	exit 3
	;;
esac

:
EOF
 		rm $N
reboot
echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac    
      
exit 0
